name: "Terraform plan workflow"

on:
  workflow_call:
    inputs:
      type:
        required: true
        type: string
    outputs:
      id_list:
        description: "The first output string"
        value: ${{ jobs.retrieve.outputs.id_list }}

jobs:
  retrieve:
    name: "Retrieving"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout the Terraform code"
        uses: actions/checkout@v2
      - name: deploy
        run: |
          echo "Folder 1 deploy"
    outputs:
      id_list: "[\"1324\", \"9982\"]"
