name: "Terraform plan workflow"

on:
  workflow_call:
    inputs:
      type:
        required: true
        type: string
    outputs:
      id_list:
        description: "The first output string"
        value: ${{ jobs.retrieve.outputs.output1 }}

jobs:
  retrieve:
    name: "Retrieving"
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step2.outputs.test }}
    steps:
      - name: "Checkout the Terraform code"
        uses: actions/checkout@v2
      - id: "step2"
        name: deploy
        run: |
          echo "::set-output name=test::[\"1324\", \"9982\"]"
