name: "Terraform plan workflow"

on:
  workflow_call:
    inputs:
      regions:
        required: true
        type: string
      account_id:
        required: true
        type: string

jobs:
  folder1:
    name: "Folder 1"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        region: ${{fromJson(inputs.regions)}}
        account_id: ${{fromJson(inputs.account_id)}}
    steps:
      - name: "Checkout the Terraform code"
        uses: actions/checkout@v2
      - name: deploy
        run: |
          echo "Folder 1 deploy: ${{ matrix.account_id }}" - ${{ matrix.region }}"

  folder2:
    needs: folder1
    name: "Folder 2 - ${{inputs.account_id}}-${{inputs.region}}"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: deploy
        run: |
          echo "Folder 2 deploy - ${{ matrix.account_id }}" - home region"
