name: Deploy
on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '**/README.md'
      
jobs:
  setup:
    runs-on: ubuntu-latest
    environment: nonprod
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7
  fetch:
    needs: setup
    uses: ./.github/workflows/get-by-type.yaml
    with:
      type: "infra"
