name: Deploy
on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '**/README.md'
      
jobs:
  setup:
    runs-on: ubuntu-latest
    environment: nonprod
    strategy:
      matrix:
        region: [ 'eu-central-1', 'eu-west-1' ]
        account: [ '1234', '5678']
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7
  deploy:
    uses: ./.github/workflows/inner.yaml
    needs: setup
    with:
      account_id: ${{ matrix.account }}
      region: ${{ matrix.region }}
