name: CHECK
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths-ignore:
      - '**/README.md'
      
jobs:
  setup:
    runs-on: ubuntu-latest
    environment: nonprod
    steps:
      - name: test
        run: |
          echo "test"
