name: Deploy
on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '**/README.md'
      
jobs:
  deploy-nonprod:
    runs-on: ubuntu-latest
    environment: nonprod
    strategy:
      matrix:
        region: [ 'eu-central-1', 'eu-west-1' ]
        account: [ '1234', '5678']
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7
      - name: Install software packages
        run: |
          sudo apt-get update
          sudo apt-get install jq
      - name: test
        run: |
          echo ${{ matrix.region }}
          echo ${{ matrix.account }}
