name: Deploy
on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**/README.md'
      
jobs:
  deploy-sandbox:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        region: [ 'eu-central-1', 'eu-west-1' ]
    steps:
      - uses: actions/checkout@v2
      - name: Install software packages
        run: |
          sudo apt-get update
          sudo apt-get install jq terraform awscli
      - name: test
        run: |
          terraform -version
          awscli -version
          jq -version
          echo ${{ matrix.region }}
